import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import type { SlotId, SlotValue, LeadDraft } from "@/lib/ai/types";
import { SLOT_ORDER } from "@/lib/ai/types";
import { leadPayload } from "@/lib/ai/lead-view";
import { isValidEmail, isValidName } from "@/lib/validation";
import { effectiveDailyCap, loadTenantConfig } from "@/lib/tenants/config";
import { readLeadsDatabaseConfig } from "@/lib/db/config";
import { getLeadsDatabase } from "@/lib/db/client";
import { ensureSchema, insertEnquiry } from "@/lib/db/store";
import { clientKey } from "@/lib/rate-limit";
import { checkSharedRateLimit } from "@/lib/rate-limit/shared";

/**
 * Public intake for completed enquiries from hosted capture pages.
 *
 * Status codes, each deliberate:
 *
 *  - **400** — the body could not be used. No row.
 *  - **404** — unknown slug, disabled slug, or no datastore configured. All
 *    three answer identically so a dead or killed tenant leaves nothing to
 *    probe.
 *  - **413** — body over the size cap. No row.
 *  - **429** — a limit tripped: per-IP, global daily budget, or the tenant's
 *    own daily cap. `Retry-After` says when to come back.
 *  - **500** — validated but the datastore write failed. The client may
 *    retry; de-duplication on the event id makes that safe.
 *  - **201** — stored (or already stored: a retried submission gets the same
 *    201 without storing twice).
 *
 * Abuse control lives here rather than in hope: per-IP minute/hour windows
 * and a global daily budget as on the assistant route, plus this phase's new
 * per-tenant daily cap, a kill switch (the 404 above), payload size caps and
 * two cheap bot tells — a filled honeypot field, or a "conversation" finished
 * faster than a person can read the first question.
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const PER_MINUTE = { limit: 10, windowMs: 60_000 };
const PER_HOUR = { limit: 60, windowMs: 60 * 60_000 };
/** Ceiling across all tenants; the wallet protection behind the per-tenant caps. */
const GLOBAL_PER_DAY = { limit: 2_000, windowMs: 24 * 60 * 60_000 };

/** A completed conversation is at most a few KB; this is generous. */
const MAX_BODY_BYTES = 16 * 1024;

/** Fastest plausible human completion, reading at least one question. */
const MIN_ELAPSED_MS = 1_500;

function tooMany(retryAfterSeconds: number) {
  return NextResponse.json(
    { error: "Too many requests. Please wait a moment and try again." },
    { status: 429, headers: { "Retry-After": String(retryAfterSeconds) } },
  );
}

function badRequest(message = "Malformed request.") {
  return NextResponse.json({ error: message }, { status: 400 });
}

/** Unknown slug, killed tenant, no datastore: one answer, nothing to probe. */
function notFound() {
  return NextResponse.json({ error: "Not found." }, { status: 404 });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function parseSlotValue(value: unknown): SlotValue | null {
  if (!isRecord(value)) return null;
  const { display, code } = value;
  if (typeof display !== "string" || display.length === 0 || display.length > 200) {
    return null;
  }
  if (code !== undefined && (typeof code !== "string" || code.length > 60)) return null;
  return code === undefined ? { display } : { display, code };
}

/** Same shape the capture page holds in memory; validated hard on arrival. */
function parseLead(value: unknown): LeadDraft | null {
  if (!isRecord(value)) return null;
  const slots: Partial<Record<SlotId, SlotValue>> = {};

  if (!isRecord(value.slots)) return null;
  let counted = 0;
  for (const [key, raw] of Object.entries(value.slots)) {
    if (!SLOT_ORDER.includes(key as SlotId)) continue;
    const parsed = parseSlotValue(raw);
    if (!parsed) return null;
    slots[key as SlotId] = parsed;
    counted += 1;
  }
  if (counted === 0) return null;

  if (!isRecord(value.contact)) return null;
  const { name, email, company, phone } = value.contact;
  if (typeof name !== "string" || typeof email !== "string") return null;
  const trimmedName = name.trim().slice(0, 120);
  const trimmedEmail = email.trim().slice(0, 254);
  // An enquiry nobody can reply to is not an enquiry. The engine will not
  // complete a conversation without these either, so requiring them here is
  // consistency, not policy.
  if (!isValidName(trimmedName) || !isValidEmail(trimmedEmail)) return null;

  return {
    slots,
    contact: {
      name: trimmedName,
      email: trimmedEmail,
      ...(typeof company === "string" ? { company: company.trim().slice(0, 160) } : {}),
      ...(typeof phone === "string" ? { phone: phone.trim().slice(0, 40) } : {}),
    },
  };
}

/**
 * A stable id for the whole submission, generated by the page once per
 * completed conversation and reused across retries. If a client does not
 * send one (an old bundle, or a hand-built request), a deterministic one is
 * derived from the enquiry's own content, so the same enquiry resubmitted
 * still lands on one row.
 */
function normaliseEventId(value: unknown, fingerprintSeed: string): string {
  if (typeof value === "string" && /^enq_[0-9a-zA-Z-]{6,64}$/.test(value)) {
    return value;
  }
  const hash = createHash("sha256").update(fingerprintSeed).digest("hex").slice(0, 32);
  return `enq_h_${hash}`;
}

export async function POST(request: Request): Promise<NextResponse> {
  // --- flood limits first: they are cheap and defend everything below ---
  const minute = await checkSharedRateLimit(clientKey(request.headers, "leads-min"), PER_MINUTE);
  if (!minute.allowed) return tooMany(minute.retryAfterSeconds);

  const hour = await checkSharedRateLimit(clientKey(request.headers, "leads-hr"), PER_HOUR);
  if (!hour.allowed) return tooMany(hour.retryAfterSeconds);

  // --- size caps before any parsing work ---
  const declaredLength = Number(request.headers.get("content-length") ?? "0");
  if (declaredLength > MAX_BODY_BYTES) {
    return NextResponse.json({ error: "Request too large." }, { status: 413 });
  }

  let rawBody: string;
  try {
    rawBody = await request.text();
  } catch {
    return badRequest();
  }
  if (rawBody.length > MAX_BODY_BYTES) {
    return NextResponse.json({ error: "Request too large." }, { status: 413 });
  }

  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return badRequest();
  }
  if (!isRecord(body)) return badRequest();

  const slug = typeof body.slug === "string" ? body.slug.trim().toLowerCase() : "";
  if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(slug)) return badRequest();

  const lead = parseLead(body.lead);
  if (!lead) return badRequest();

  // --- tenant: unknown, disabled or unprovisioned all look identical ---
  const tenant = await loadTenantConfig(slug);
  if (!tenant) return notFound();

  const meta = isRecord(body.meta) ? body.meta : {};
  const elapsedMs =
    typeof meta.elapsedMs === "number" && Number.isFinite(meta.elapsedMs)
      ? meta.elapsedMs
      : Number.MAX_SAFE_INTEGER;

  // --- bot tells: dropped quietly after the flood limits have had their say,
  //     but before anything is counted against the tenant ---
  if (typeof body.companyWebsite === "string" && body.companyWebsite.trim() !== "") {
    console.warn("[leads] honeypot field filled; dropping submission");
    // A plausible success: teaching a farm which requests fail helps nobody.
    return NextResponse.json({ received: true }, { status: 201 });
  }
  if (elapsedMs < MIN_ELAPSED_MS) {
    console.warn(`[leads] submitted after ${String(elapsedMs)}ms; dropping submission`);
    return NextResponse.json({ received: true }, { status: 201 });
  }

  // --- per-tenant daily cap: counted only for submissions that would store,
  //     so garbage cannot drain a tenant's budget for it ---
  const dayWindow = { limit: effectiveDailyCap(tenant), windowMs: 24 * 60 * 60_000 };
  const tenantBudget = await checkSharedRateLimit(`leads-tenant:${slug}`, dayWindow);
  if (!tenantBudget.allowed) {
    console.warn(`[leads] tenant ${slug} hit its daily cap`);
    return tooMany(tenantBudget.retryAfterSeconds);
  }
  const globalBudget = await checkSharedRateLimit("leads-global", GLOBAL_PER_DAY);
  if (!globalBudget.allowed) {
    console.warn("[leads] global daily enquiry budget reached");
    return tooMany(globalBudget.retryAfterSeconds);
  }

  const eventId = normaliseEventId(
    body.eventId,
    `${slug}|${lead.contact?.email ?? ""}|${SLOT_ORDER.map((slot) => lead.slots[slot]?.display ?? "").join("|")}`,
  );

  try {
    const sql = getLeadsDatabase(readLeadsDatabaseConfigOrThrow());
    await ensureSchema(sql);

    const result = await insertEnquiry(sql, {
      tenantSlug: slug,
      eventId,
      summary: `New enquiry for ${tenant.companyName}`,
      payload: leadPayload(lead),
      contactEmail: lead.contact?.email ?? "",
    });

    if (!result.inserted) {
      // Already stored: a retried POST. The original 201 stands.
      console.info(`[leads] duplicate enquiry ${eventId} for ${slug}; acknowledged`);
    }
    return NextResponse.json(
      { received: true, reference: leadPayload(lead).reference },
      { status: 201 },
    );
  } catch (error) {
    console.error(`[leads] failed to store enquiry ${eventId} for ${slug}`, error);
    return NextResponse.json({ error: "Could not store enquiry." }, { status: 500 });
  }
}

/**
 * Unreachable `null` in practice: a tenant was loaded moments ago, which only
 * happens with a datastore configured. Kept as an explicit throw rather than a
 * non-null assertion so the invariant is stated, not assumed.
 */
function readLeadsDatabaseConfigOrThrow(): { url: string } {
  const config = readLeadsDatabaseConfig();
  if (!config) throw new Error("leads route reached without LEADS_DATABASE_URL");
  return config;
}
