import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

/**
 * Browser tab icon: the same facilities-tag mark used by the wordmark.
 *
 * Generated by `next/og` rather than shipped as a binary, so it stays in step
 * with the brand mark and needs no image tooling. Drawn as a path — a glyph
 * would trigger a font fetch at build time.
 */
export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#15231f",
          borderRadius: 7,
        }}
      >
        <svg width="24" height="24" viewBox="0 0 28 28">
          <circle
            cx="8"
            cy="8"
            r="2.3"
            fill="none"
            stroke="#f0b429"
            strokeWidth="1.8"
          />
          <path
            d="M9.5 17.5 13.25 21.25 21 12"
            fill="none"
            stroke="#f0b429"
            strokeWidth="2.6"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </div>
    ),
    size,
  );
}
