import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

/**
 * Browser tab icon: the same enclosed tick used by the wordmark.
 *
 * Generated by `next/og` rather than shipped as a binary, so it stays in step
 * with the brand mark and needs no image tooling. Drawn as a path — a glyph
 * would trigger a font fetch at build time.
 */
export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#0b1524",
          borderRadius: 7,
        }}
      >
        <svg width="22" height="22" viewBox="0 0 24 24">
          <path
            d="M5 12.5 10 17.5 19 7"
            fill="none"
            stroke="#ffffff"
            strokeWidth="3"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </div>
    ),
    size,
  );
}
