/**
 * Shared pieces for the images generated by `next/og`: the social card, the
 * favicon and the home-screen icon.
 *
 * Satori renders this JSX to PNG at build time. It resolves no CSS, so it
 * cannot read the `@theme` tokens in `app/globals.css` and every colour has to
 * be restated as a literal. `BRAND_COLORS` exists so the restatement happens
 * once, in a place obviously coupled to the stylesheet, rather than as loose
 * hexes scattered through three image routes.
 *
 * Keep these in step with the `@theme` block in `app/globals.css`.
 */
export const BRAND_COLORS = {
  /** --color-ink */
  ink: "#15231f",
  /** --color-paper */
  paper: "#f1f3ee",
  /** --color-brand */
  brand: "#f0b429",
  /** Muted body text on the ink ground. Between --color-hairline and ink. */
  onInk: "#9fb0a3",
  /** One step quieter again, for the footer line of the card. */
  onInkFaint: "#8ea298",
  white: "#ffffff",
} as const;

/**
 * The four-square mark, in divs.
 *
 * Mirrors `BrandMark` in `components/marketing/Wordmark.tsx`. Drawn with
 * flexbox rather than `<svg>` because Satori's SVG support is narrower than
 * its layout support, and this shape needs no curves.
 */
export function MarkTiles({
  size,
  gap,
  tint,
}: {
  /** Overall width and height in pixels. */
  size: number;
  /** Space between the tiles. */
  gap: number;
  /** Colour of the three unfilled tiles. The fourth is always brand amber. */
  tint: string;
}) {
  const tile = (size - gap) / 2;
  const square = (background: string) => (
    <div style={{ width: tile, height: tile, background }} />
  );

  return (
    <div style={{ display: "flex", flexDirection: "column", gap }}>
      <div style={{ display: "flex", gap }}>
        {square(tint)}
        {square(tint)}
      </div>
      <div style={{ display: "flex", gap }}>
        {square(tint)}
        {square(BRAND_COLORS.brand)}
      </div>
    </div>
  );
}
