import type { Prospect } from "@/types/prospect";

/**
 * Fictional seed data for development.
 *
 * Company names, domains, contact names and email addresses are invented and
 * do not refer to real businesses or people. Replace wholesale with the real
 * outreach list — this exists so the dashboard can be built and judged against
 * a realistic volume and spread of records.
 *
 * Dates are anchored around August 2026.
 */
export const SEED_PROSPECTS: Prospect[] = [
  {
    id: "p-001",
    companyName: "Brightwell Facilities",
    website: "https://brightwellfacilities.co.uk",
    city: "Manchester",
    country: "United Kingdom",
    companyType: "facilities_management",
    contactName: "R. Hale",
    contactEmail: "hello@brightwellfacilities.co.uk",
    contactSource: "google_maps",
    notes: "12 staff. Runs contracts for two business parks.",
    personalizationAngle:
      "Site says 'quote within 24 hours' — worth asking what that costs them out of hours.",
    status: "interested",
    dateAdded: "2026-07-02",
    dateContacted: "2026-07-06",
    dateFollowedUp: "2026-07-14",
    response: "Asked what it would cost and whether it handles multi-site enquiries.",
    nextAction: { description: "Send pricing + multi-site answer", dueDate: "2026-08-11" },
  },
  {
    id: "p-002",
    companyName: "Kestrel Commercial Cleaning",
    website: "https://kestrelcommercial.co.uk",
    city: "Leeds",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "D. Okafor",
    contactEmail: "info@kestrelcommercial.co.uk",
    contactSource: "company_website",
    notes: "Enquiry form is 9 fields long. Slow to load on mobile.",
    personalizationAngle: "Their own form asks for floor area — the assistant does that conversationally.",
    status: "demo_sent",
    dateAdded: "2026-06-24",
    dateContacted: "2026-06-29",
    dateFollowedUp: "2026-07-20",
    response: "Wants to see it working before any call.",
    nextAction: { description: "Chase demo feedback", dueDate: "2026-08-06" },
  },
  {
    id: "p-003",
    companyName: "Sable & Stone Cleaning Co",
    website: "https://sableandstone.co.uk",
    city: "London",
    country: "United Kingdom",
    companyType: "office_cleaning",
    contactName: "M. Idris",
    contactEmail: "m.idris@sableandstone.co.uk",
    contactSource: "linkedin",
    notes: "Boutique, 30ish offices in zone 1–2. Positions on service quality.",
    personalizationAngle: "Posts about losing weekend enquiries to faster competitors.",
    status: "proposal",
    dateAdded: "2026-06-20",
    dateContacted: "2026-06-25",
    dateFollowedUp: "2026-07-28",
    response: "Wants a written proposal with a 3-month trial price.",
    nextAction: { description: "Proposal follow-up call", dueDate: "2026-08-14" },
  },
  {
    id: "p-004",
    companyName: "Northgate Contract Services",
    website: "https://northgatecontract.co.uk",
    city: "Newcastle upon Tyne",
    country: "United Kingdom",
    companyType: "contract_cleaning",
    contactName: "S. Rutherford",
    contactEmail: "enquiries@northgatecontract.co.uk",
    contactSource: "directory",
    notes: "No enquiry form at all — phone number only.",
    personalizationAngle: "No web capture whatsoever; whole pitch is 'stop losing after-hours enquiries'.",
    status: "contacted",
    dateAdded: "2026-07-18",
    dateContacted: "2026-07-24",
  },
  {
    id: "p-005",
    companyName: "PureLine Cleaning Group",
    website: "https://purelinegroup.co.uk",
    city: "Birmingham",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "A. Whitcombe",
    contactEmail: "a.whitcombe@purelinegroup.co.uk",
    contactSource: "linkedin",
    notes: "Around 60 staff. Three regional depots.",
    personalizationAngle: "Hiring an office admin — the assistant is the cheaper version of that role.",
    status: "replied",
    dateAdded: "2026-07-08",
    dateContacted: "2026-07-13",
    response: "Interested in principle, asked me to come back in September.",
    nextAction: { description: "Re-approach after summer", dueDate: "2026-09-01" },
  },
  {
    id: "p-006",
    companyName: "Halcyon Office Care",
    website: "https://halcyonofficecare.co.uk",
    city: "Bristol",
    country: "United Kingdom",
    companyType: "office_cleaning",
    contactName: "J. Pemberton",
    contactEmail: "hello@halcyonofficecare.co.uk",
    contactSource: "google_maps",
    notes: "Strong reviews, weak website.",
    personalizationAngle: "Reviews repeatedly praise responsiveness — lean into protecting that.",
    status: "contacted",
    dateAdded: "2026-07-27",
    dateContacted: "2026-08-03",
  },
  {
    id: "p-007",
    companyName: "Merrow Facilities Support",
    website: "https://merrowfacilities.co.uk",
    city: "Reading",
    country: "United Kingdom",
    companyType: "facilities_management",
    contactEmail: "office@merrowfacilities.co.uk",
    contactSource: "directory",
    notes: "Generic inbox only. No named contact found yet.",
    personalizationAngle: "Tenders for council contracts — structured enquiry data may help their bids.",
    status: "no_response",
    dateAdded: "2026-06-22",
    dateContacted: "2026-06-26",
    dateFollowedUp: "2026-07-09",
  },
  {
    id: "p-008",
    companyName: "Clearview Window Services",
    website: "https://clearviewwindows.co.uk",
    city: "Sheffield",
    country: "United Kingdom",
    companyType: "window_cleaning",
    contactName: "T. Bhandari",
    contactEmail: "t.bhandari@clearviewwindows.co.uk",
    contactSource: "google_maps",
    notes: "Narrow service line — may be a poor fit for a quoting assistant.",
    personalizationAngle: "Quotes depend on storeys and access; good test of the follow-up questions.",
    status: "lost",
    dateAdded: "2026-06-25",
    dateContacted: "2026-07-01",
    dateFollowedUp: "2026-07-15",
    response: "Said their jobs are too standardised to need this.",
  },
  {
    id: "p-009",
    companyName: "Ardent Clean Ltd",
    website: "https://ardentclean.co.uk",
    city: "Glasgow",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "F. MacAulay",
    contactEmail: "f.macaulay@ardentclean.co.uk",
    contactSource: "linkedin",
    notes: "Owner-operator, very active on LinkedIn.",
    personalizationAngle: "Posted about missing two tenders because quotes went out late.",
    status: "won",
    dateAdded: "2026-06-21",
    dateContacted: "2026-06-27",
    dateFollowedUp: "2026-07-16",
    response: "Signed up for the first pilot at the trial rate.",
  },
  {
    id: "p-010",
    companyName: "Thistlewood Cleaning",
    website: "https://thistlewoodcleaning.co.uk",
    city: "Edinburgh",
    country: "United Kingdom",
    companyType: "contract_cleaning",
    contactName: "K. Ferrier",
    contactEmail: "k.ferrier@thistlewoodcleaning.co.uk",
    contactSource: "trade_association",
    notes: "Member of a regional cleaning association — possible referral route.",
    personalizationAngle: "Association listing mentions same-day quotes as a differentiator.",
    status: "replied",
    dateAdded: "2026-07-10",
    dateContacted: "2026-07-16",
    dateFollowedUp: "2026-07-30",
    response: "Asked whether it can hand off to a human mid-conversation.",
  },
  {
    id: "p-011",
    companyName: "Vantage Hygiene Services",
    website: "https://vantagehygiene.co.uk",
    city: "Cardiff",
    country: "United Kingdom",
    companyType: "specialist_cleaning",
    contactName: "L. Prosser",
    contactEmail: "l.prosser@vantagehygiene.co.uk",
    contactSource: "company_website",
    notes: "Healthcare and lab cleaning. Compliance-heavy quoting.",
    personalizationAngle: "Their quotes need compliance detail — good structured-data story.",
    status: "demo_sent",
    dateAdded: "2026-07-01",
    dateContacted: "2026-07-07",
    dateFollowedUp: "2026-07-31",
    response: "Watched the demo, asked about data handling and GDPR.",
    nextAction: { description: "Send data-handling one-pager", dueDate: "2026-08-13" },
  },
  {
    id: "p-012",
    companyName: "Oakfield Commercial Care",
    website: "https://oakfieldcommercial.co.uk",
    city: "Nottingham",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "P. Ndiaye",
    contactEmail: "p.ndiaye@oakfieldcommercial.co.uk",
    contactSource: "google_maps",
    notes: "Mid-size. Enquiry form goes to a shared inbox.",
    personalizationAngle: "Shared inbox means nobody owns response time.",
    status: "new",
    dateAdded: "2026-08-11",
  },
  {
    id: "p-013",
    companyName: "Silverbrook Cleaning Partners",
    website: "https://silverbrookpartners.co.uk",
    city: "Milton Keynes",
    country: "United Kingdom",
    companyType: "office_cleaning",
    contactName: "E. Marsden",
    contactEmail: "e.marsden@silverbrookpartners.co.uk",
    contactSource: "linkedin",
    notes: "Recently rebranded. New site, still no quote flow.",
    personalizationAngle: "Just invested in a rebrand — receptive to looking modern.",
    status: "new",
    dateAdded: "2026-08-10",
  },
  {
    id: "p-014",
    companyName: "Harbourlight Facilities",
    website: "https://harbourlightfm.co.uk",
    city: "Southampton",
    country: "United Kingdom",
    companyType: "facilities_management",
    contactName: "C. Alderton",
    contactEmail: "c.alderton@harbourlightfm.co.uk",
    contactSource: "directory",
    notes: "Marine and port facilities. Unusual niche.",
    personalizationAngle: "Port work means irregular, high-value enquiries worth qualifying properly.",
    status: "contacted",
    dateAdded: "2026-07-21",
    dateContacted: "2026-07-29",
  },
  {
    id: "p-015",
    companyName: "Redmoor Janitorial",
    website: "https://redmoorjanitorial.co.uk",
    city: "Liverpool",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "N. Quayle",
    contactEmail: "n.quayle@redmoorjanitorial.co.uk",
    contactSource: "google_maps",
    notes: "Family run, 20+ years. Sceptical of anything 'AI'.",
    personalizationAngle: "Frame as an assistant for the office manager, not as AI.",
    status: "no_response",
    dateAdded: "2026-06-28",
    dateContacted: "2026-07-03",
    dateFollowedUp: "2026-07-17",
  },
  {
    id: "p-016",
    companyName: "Crisp & Clear Cleaning",
    website: "https://crispandclear.co.uk",
    city: "Brighton",
    country: "United Kingdom",
    companyType: "office_cleaning",
    contactName: "H. Ellery",
    contactEmail: "h.ellery@crispandclear.co.uk",
    contactSource: "company_website",
    notes: "Serves co-working spaces and creative studios.",
    personalizationAngle: "Their clients expect instant everything — slow quotes stand out badly.",
    status: "interested",
    dateAdded: "2026-07-05",
    dateContacted: "2026-07-11",
    dateFollowedUp: "2026-08-04",
    response: "Wants a call, asked for times week commencing 17 Aug.",
    nextAction: { description: "Book intro call", dueDate: "2026-08-15" },
  },
  {
    id: "p-017",
    companyName: "Lambert Contract Cleaning",
    website: "https://lambertcontract.co.uk",
    city: "Coventry",
    country: "United Kingdom",
    companyType: "contract_cleaning",
    contactName: "G. Sowande",
    contactEmail: "g.sowande@lambertcontract.co.uk",
    contactSource: "directory",
    notes: "Industrial units and warehousing.",
    personalizationAngle: "Warehouse quotes hinge on floor area and shift pattern — easy to script.",
    status: "contacted",
    dateAdded: "2026-07-14",
    dateContacted: "2026-07-20",
    dateFollowedUp: "2026-08-01",
  },
  {
    id: "p-018",
    companyName: "Greenway Site Services",
    website: "https://greenwaysite.co.uk",
    city: "Norwich",
    country: "United Kingdom",
    companyType: "specialist_cleaning",
    contactEmail: "admin@greenwaysite.co.uk",
    contactSource: "google_maps",
    notes: "Construction cleans and post-build sparkle cleans.",
    personalizationAngle: "Post-build jobs are one-off and price-sensitive — fast quoting wins them.",
    status: "new",
    dateAdded: "2026-08-05",
  },
  {
    id: "p-019",
    companyName: "Ashcroft Cleaning Solutions",
    website: "https://ashcroftsolutions.co.uk",
    city: "Leicester",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "V. Ranganathan",
    contactEmail: "v.r@ashcroftsolutions.co.uk",
    contactSource: "linkedin",
    notes: "Expanding into a second city this year.",
    personalizationAngle: "Growth means more enquiries than the current admin can handle.",
    status: "replied",
    dateAdded: "2026-07-09",
    dateContacted: "2026-07-15",
    response: "Asked for a one-line summary of pricing before engaging further.",
    nextAction: { description: "Send short pricing reply", dueDate: "2026-08-08" },
  },
  {
    id: "p-020",
    companyName: "Beacon Hill Facilities",
    website: "https://beaconhillfm.co.uk",
    city: "Belfast",
    country: "United Kingdom",
    companyType: "facilities_management",
    contactName: "O. Devlin",
    contactEmail: "o.devlin@beaconhillfm.co.uk",
    contactSource: "trade_association",
    notes: "Northern Ireland only. Watch VAT/contract differences.",
    personalizationAngle: "Regional operator competing with national FM firms on responsiveness.",
    status: "new",
    dateAdded: "2026-08-08",
  },
  {
    id: "p-021",
    companyName: "Tidewell Cleaning Ltd",
    website: "https://tidewellcleaning.co.uk",
    city: "Plymouth",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "B. Carew",
    contactEmail: "b.carew@tidewellcleaning.co.uk",
    contactSource: "google_maps",
    notes: "Small team, owner answers the phone himself.",
    personalizationAngle: "Owner is the bottleneck — the pitch is giving him his evenings back.",
    status: "contacted",
    dateAdded: "2026-07-25",
    dateContacted: "2026-08-07",
  },
  {
    id: "p-022",
    companyName: "Marchmont Office Services",
    website: "https://marchmontoffice.co.uk",
    city: "Aberdeen",
    country: "United Kingdom",
    companyType: "office_cleaning",
    contactName: "I. Strachan",
    contactEmail: "i.strachan@marchmontoffice.co.uk",
    contactSource: "directory",
    notes: "Energy-sector offices. Quiet market right now.",
    personalizationAngle: "Fewer enquiries means converting each one matters more.",
    status: "no_response",
    dateAdded: "2026-06-30",
    dateContacted: "2026-07-04",
    dateFollowedUp: "2026-07-18",
  },
  {
    id: "p-023",
    companyName: "Fernhill Hygiene",
    website: "https://fernhillhygiene.co.uk",
    city: "Swansea",
    country: "United Kingdom",
    companyType: "specialist_cleaning",
    contactName: "R. Vaughan",
    contactEmail: "r.vaughan@fernhillhygiene.co.uk",
    contactSource: "company_website",
    notes: "Food production and kitchen deep cleans.",
    personalizationAngle: "Compliance schedules make their quotes genuinely complicated.",
    status: "new",
    dateAdded: "2026-08-12",
  },
  {
    id: "p-024",
    companyName: "Bramble Court Cleaning",
    website: "https://bramblecourt.co.uk",
    city: "York",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "A. Fenwick",
    contactEmail: "a.fenwick@bramblecourt.co.uk",
    contactSource: "google_maps",
    notes: "Heritage buildings and small commercial sites.",
    personalizationAngle: "Site visits currently required before every quote.",
    status: "demo_sent",
    dateAdded: "2026-07-03",
    dateContacted: "2026-07-10",
    dateFollowedUp: "2026-08-02",
    response: "Liked the demo, wants to know if it can book a site visit.",
  },
  {
    id: "p-025",
    companyName: "Stanton Ridge Services",
    website: "https://stantonridge.co.uk",
    city: "Derby",
    country: "United Kingdom",
    companyType: "contract_cleaning",
    contactName: "W. Aldridge",
    contactEmail: "w.aldridge@stantonridge.co.uk",
    contactSource: "linkedin",
    notes: "Manufacturing sites, shift-pattern cleaning.",
    personalizationAngle: "Shift patterns are exactly the sort of detail enquiries never include.",
    status: "new",
    dateAdded: "2026-08-01",
  },
  {
    id: "p-026",
    companyName: "Wexford Clean Group",
    website: "https://wexfordclean.co.uk",
    city: "Luton",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactEmail: "enquiries@wexfordclean.co.uk",
    contactSource: "directory",
    notes: "Airport-adjacent business parks. No named contact yet.",
    personalizationAngle: "24/7 operations nearby — out-of-hours enquiries are likely.",
    status: "new",
    dateAdded: "2026-07-30",
  },
  {
    id: "p-027",
    companyName: "Alderman Facilities",
    website: "https://aldermanfacilities.co.uk",
    city: "Croydon",
    country: "United Kingdom",
    companyType: "facilities_management",
    contactName: "S. Ogundele",
    contactEmail: "s.ogundele@aldermanfacilities.co.uk",
    contactSource: "linkedin",
    notes: "Mixed FM: cleaning, security, grounds.",
    personalizationAngle: "Multi-service enquiries need triage before anyone can quote.",
    status: "proposal",
    dateAdded: "2026-06-26",
    dateContacted: "2026-07-02",
    dateFollowedUp: "2026-08-05",
    response: "Proposal with their branding requested; decision at month end.",
    nextAction: { description: "Check in before month-end decision", dueDate: "2026-08-24" },
  },
  {
    id: "p-028",
    companyName: "Pinewood Commercial Clean",
    website: "https://pinewoodcommercial.co.uk",
    city: "Ipswich",
    country: "United Kingdom",
    companyType: "commercial_cleaning",
    contactName: "M. Threlfall",
    contactEmail: "m.threlfall@pinewoodcommercial.co.uk",
    contactSource: "google_maps",
    notes: "Retail parks and small industrial estates.",
    personalizationAngle: "Retail clients expect quotes same day.",
    status: "contacted",
    dateAdded: "2026-07-22",
    dateContacted: "2026-07-28",
  },
  {
    id: "p-029",
    companyName: "Cobalt Care Cleaning",
    website: "https://cobaltcare.co.uk",
    city: "Stoke-on-Trent",
    country: "United Kingdom",
    companyType: "specialist_cleaning",
    contactName: "Y. Farooq",
    contactEmail: "y.farooq@cobaltcare.co.uk",
    contactSource: "trade_association",
    notes: "Care homes and supported living.",
    personalizationAngle: "Care sector buyers ask a fixed set of compliance questions every time.",
    status: "interested",
    dateAdded: "2026-07-07",
    dateContacted: "2026-07-12",
    dateFollowedUp: "2026-07-27",
    response: "Positive, wants to involve their operations manager.",
  },
  {
    id: "p-030",
    companyName: "Willowbank Cleaning Services",
    website: "https://willowbankcleaning.co.uk",
    city: "Exeter",
    country: "United Kingdom",
    companyType: "office_cleaning",
    contactName: "D. Trelawny",
    contactEmail: "d.trelawny@willowbankcleaning.co.uk",
    contactSource: "company_website",
    notes: "Good site, already has a multi-step quote form.",
    personalizationAngle: "Already believes in capturing detail — this is the upgrade, not the idea.",
    status: "replied",
    dateAdded: "2026-07-13",
    dateContacted: "2026-07-19",
    dateFollowedUp: "2026-08-06",
    response: "Asked how it differs from the form they already have.",
    nextAction: { description: "Answer 'why not just a form?'", dueDate: "2026-08-12" },
  },
  {
    id: "p-031",
    companyName: "Trentmoor Site Hygiene",
    website: "https://trentmoorhygiene.co.uk",
    city: "Wolverhampton",
    country: "United Kingdom",
    companyType: "specialist_cleaning",
    contactName: "J. Ashworth",
    contactEmail: "j.ashworth@trentmoorhygiene.co.uk",
    contactSource: "directory",
    notes: "Waste handling and washroom services alongside cleaning.",
    personalizationAngle: "Bundled services make enquiries ambiguous — qualification helps.",
    status: "new",
    dateAdded: "2026-08-03",
  },
  {
    id: "p-032",
    companyName: "Summerfield Contract Clean",
    website: "https://summerfieldcontract.co.uk",
    city: "Preston",
    country: "United Kingdom",
    companyType: "contract_cleaning",
    contactName: "L. Boothroyd",
    contactEmail: "l.boothroyd@summerfieldcontract.co.uk",
    contactSource: "google_maps",
    notes: "Schools and academies. Highly seasonal.",
    personalizationAngle: "Summer holiday deep cleans are booked in a narrow window.",
    status: "contacted",
    dateAdded: "2026-07-16",
    dateContacted: "2026-07-23",
  },
];
